$kind: http-example
request:
  url: "{{base_url}}/tasks/{{task_id}}"
  method: GET
  headers:
    Authorization: Bearer {{token}}
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: |-
      {
        "data": {
          "id": 1,
          "title": "Implementasi fitur login",
          "status": "in_progress",
          "deadline": "2026-07-10T10:00:00Z",
          "assignee": { "id": 2, "name": "Anisetus" }
        }
      }
order: 1000
