$kind: http-example
request:
  url: "{{base_url}}/tasks/{{task_id}}"
  method: PUT
  headers:
    Authorization: Bearer {{token}}
    Content-Type: application/json
  body:
    type: text
    content: |-
      {
        "title": "Setup database PostgreSQL (Updated)",
        "description": "Update deskripsi task",
        "status": "in_progress",
        "deadline": "2026-07-12T18:00:00Z",
        "assignee_id": 3
      }
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: |-
      {
        "message": "Task berhasil diupdate",
        "data": { "id": 5, "title": "Setup database PostgreSQL (Updated)", "status": "in_progress" }
      }
order: 1000
