$kind: http-example
request:
  url: "{{base_url}}/tasks"
  method: POST
  headers:
    Authorization: Bearer {{token}}
    Content-Type: application/json
  body:
    type: text
    content: |-
      {
        "title": "Setup database PostgreSQL",
        "description": "Buat tabel users dan tasks sesuai schema yang ditentukan",
        "status": "todo",
        "deadline": "2026-07-10T10:00:00Z",
        "assignee_id": 2
      }
response:
  statusCode: 400
  statusText: Bad Request
  body:
    type: text
    content: |-
      {
        "error": "Assignee tidak ditemukan"
      }
order: 2000
