$kind: http-request
description: Ambil semua task beserta nama assignee.
url: "{{base_url}}/tasks"
method: GET
headers:
  Authorization: Bearer {{token}}
scripts:
  - type: afterResponse
    code: |-
      pm.test('Status 200 OK', () => pm.response.to.have.status(200));
      const res = pm.response.json();
      pm.test('Response memiliki array data', () => pm.expect(res.data).to.be.an('array'));
      if (res.data && res.data.length > 0) {
          pm.environment.set('task_id', res.data[0].id);
          console.log('task_id tersimpan:', res.data[0].id);
      }
    language: text/javascript
examples: ./.resources/Get All Tasks.resources/examples
order: 1000
