$kind: http-request
description: Update semua field task sekaligus.
url: "{{base_url}}/tasks/{{task_id}}"
method: PUT
headers:
  Authorization: Bearer {{token}}
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "title": "Setup database PostgreSQL (Updated)",
      "description": "Update deskripsi task",
      "status": "in_progress",
      "deadline": "2026-07-12T18:00:00Z",
      "assignee_id": 3
    }
examples: ./.resources/Update Task (Full).resources/examples
order: 4000
