$kind: http-request
description: "Update hanya status task. Pilihan: todo, in_progress, done."
url: "{{base_url}}/tasks/{{task_id}}/status"
method: PATCH
headers:
  Authorization: Bearer {{token}}
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "status": "done"
    }
examples: ./.resources/Update Status Task.resources/examples
order: 5000
