$kind: http-request
description: "Buat task baru. Field wajib: title, deadline, assignee_id."
url: "{{base_url}}/tasks"
method: POST
headers:
  Authorization: Bearer {{token}}
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "title": "Setup database PostgreSQL",
      "description": "Buat tabel users dan tasks sesuai schema yang ditentukan",
      "status": "todo",
      "deadline": "2026-07-10T10:00:00Z",
      "assignee_id": 2
    }
scripts:
  - type: afterResponse
    code: |-
      pm.test('Status 201 Created', () => pm.response.to.have.status(201));
      const res = pm.response.json();
      if (res.data) {
          pm.environment.set('task_id', res.data.id);
          console.log('task_id baru:', res.data.id);
      }
    language: text/javascript
examples: ./.resources/Create Task.resources/examples
order: 3000
