$kind: http-example
request:
  url: "{{base_url}}/tasks/{{task_id}}/status"
  method: PATCH
  headers:
    Authorization: Bearer {{token}}
    Content-Type: application/json
  body:
    type: text
    content: |-
      {
        "status": "done"
      }
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: |-
      {
        "message": "Status berhasil diupdate"
      }
order: 1000
